### ISSUE TITLE
Hi, can you please add a manifest file

### ISSUE THREAD

**Issue by TheUltra12** [RedstoneWizard08/DumbPotionsMod#1]
I’m trying to download this mod on PE it said « manifest not found » can you please put one, I REALLY wanna try it

**Comment by RedstoneWizard08** [comment]
This mod doesn't work on PE, unfortunately. This is Java only. I don't have any plans to support Minecraft bedrock. Sorry!

**Comment by TheUltra12** [comment]
Oh :(
